Repository thoth-station/ps-nlp, pull requests merged in 2021-07, with the labels that each got.

#2 included all the requirements for the build of images
  .aicoe-ci.yaml
  .s2i/bin/assemble
  .s2i/bin/run
  .s2i/environment
  .thoth.yaml
  OWNERS
  README.rst
  overlays/ps-nlp-pytorch/Pipfile
  overlays/ps-nlp-pytorch/Pipfile.lock
  overlays/ps-nlp-tensorflow-gpu/Pipfile
  overlays/ps-nlp-tensorflow-gpu/Pipfile.lock
  overlays/ps-nlp-tensorflow/Pipfile
  overlays/ps-nlp-tensorflow/Pipfile.lock
  overlays/ps-nlp/Pipfile
  overlays/ps-nlp/Pipfile.lock
Labels: approved, size/XXL

#5 Update README
  README.rst
Labels: approved, size/S

#8 Improve description
  README.rst
Labels: approved, size/M

#9 Add badge
  README.rst
Labels: approved, size/XS

#11 updated the base image for generic ds v0.0.5
  .aicoe-ci.yaml
Labels: approved, size/XS
